# Generated by Django 4.2.1 on 2023-05-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=256)),
                ('Last_Name', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=256)),
            ],
        ),
    ]
