# Generated by Django 4.2.1 on 2023-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_user_id_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=256)),
                ('Main_Category', models.CharField(max_length=256)),
                ('Sub_Category', models.CharField(max_length=256)),
                ('Product_Description', models.CharField(max_length=256)),
                ('Product_Price', models.FloatField()),
                ('Product_Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
