# Generated by Django 4.2.1 on 2023-05-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.IntegerField()),
                ('Product_ID', models.IntegerField()),
                ('Order_Status', models.CharField(default='Pending', max_length=256)),
            ],
        ),
    ]
