# Generated by Django 4.2.1 on 2023-05-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Product_Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
